// Generated by art/export.py; do not edit.
import Toybox.Lang;
import Toybox.WatchUi;

module Art {
  // Art pixels per hero sprite side; screen size = HERO * scale.
  const HERO = 32;
  const LAND_GROUND = 33;
  const IDLE0 = 0;
  const IDLE1 = 1;
  const SLEEP = 2;
  const SALUTE = 3;
  const STRIKE0 = 4;
  const STRIKE1 = 5;
  const HORSE = 6;
  const CRANE = 7;
  const FLY0 = 8;
  const FLY1 = 9;
  const MEDITATE = 10;
  const JUMP0 = 11;
  const JUMP1 = 12;

  // Hero frame for outfit 0 (commoner) .. 4 and one of the poses above.
  function hero(outfit as Number, pose as Number) {
    var ids = [
      [Rez.Drawables.hero_0_idle0, Rez.Drawables.hero_0_idle1, Rez.Drawables.hero_0_sleep, Rez.Drawables.hero_0_salute, Rez.Drawables.hero_0_strike0, Rez.Drawables.hero_0_strike1, Rez.Drawables.hero_0_horse, Rez.Drawables.hero_0_crane, Rez.Drawables.hero_0_fly0, Rez.Drawables.hero_0_fly1, Rez.Drawables.hero_0_meditate, Rez.Drawables.hero_0_jump0, Rez.Drawables.hero_0_jump1],
      [Rez.Drawables.hero_1_idle0, Rez.Drawables.hero_1_idle1, Rez.Drawables.hero_1_sleep, Rez.Drawables.hero_1_salute, Rez.Drawables.hero_1_strike0, Rez.Drawables.hero_1_strike1, Rez.Drawables.hero_1_horse, Rez.Drawables.hero_1_crane, Rez.Drawables.hero_1_fly0, Rez.Drawables.hero_1_fly1, Rez.Drawables.hero_1_meditate, Rez.Drawables.hero_1_jump0, Rez.Drawables.hero_1_jump1],
      [Rez.Drawables.hero_2_idle0, Rez.Drawables.hero_2_idle1, Rez.Drawables.hero_2_sleep, Rez.Drawables.hero_2_salute, Rez.Drawables.hero_2_strike0, Rez.Drawables.hero_2_strike1, Rez.Drawables.hero_2_horse, Rez.Drawables.hero_2_crane, Rez.Drawables.hero_2_fly0, Rez.Drawables.hero_2_fly1, Rez.Drawables.hero_2_meditate, Rez.Drawables.hero_2_jump0, Rez.Drawables.hero_2_jump1],
      [Rez.Drawables.hero_3_idle0, Rez.Drawables.hero_3_idle1, Rez.Drawables.hero_3_sleep, Rez.Drawables.hero_3_salute, Rez.Drawables.hero_3_strike0, Rez.Drawables.hero_3_strike1, Rez.Drawables.hero_3_horse, Rez.Drawables.hero_3_crane, Rez.Drawables.hero_3_fly0, Rez.Drawables.hero_3_fly1, Rez.Drawables.hero_3_meditate, Rez.Drawables.hero_3_jump0, Rez.Drawables.hero_3_jump1],
      [Rez.Drawables.hero_4_idle0, Rez.Drawables.hero_4_idle1, Rez.Drawables.hero_4_sleep, Rez.Drawables.hero_4_salute, Rez.Drawables.hero_4_strike0, Rez.Drawables.hero_4_strike1, Rez.Drawables.hero_4_horse, Rez.Drawables.hero_4_crane, Rez.Drawables.hero_4_fly0, Rez.Drawables.hero_4_fly1, Rez.Drawables.hero_4_meditate, Rez.Drawables.hero_4_jump0, Rez.Drawables.hero_4_jump1]
    ];
    return WatchUi.loadResource(ids[outfit][pose]);
  }
}
