"""Exports the pixel art for every screen size.

For each art scale p (1 art pixel = p screen pixels) this writes
resources-art-p<p>/ with nearest-neighbour scaled PNGs and drawables.xml,
maps every product in manifest.xml to its scale in monkey.jungle, and
generates source/ArtIds.mc with the resource id tables.

    python3 art/export.py

To swap in hand-drawn art, change the drawing functions in hero.py /
scene.py (or make them load your own 1x PNGs) and run this again.
"""
import os
import re
import shutil
from PIL import Image

import hero
import scene
from outfits import OUTFITS, recolour
from pixel import PALETTE

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Screen height per product; decides the art scale.
SCREEN = {
    "enduro3": 280,
    "epix2": 416, "epix2pro42mm": 390, "epix2pro47mm": 416, "epix2pro51mm": 454,
    "fenix7": 260, "fenix7pro": 260, "fenix7pronowifi": 260,
    "fenix7s": 240, "fenix7spro": 240,
    "fenix7x": 280, "fenix7xpro": 280, "fenix7xpronowifi": 280,
    "fenix843mm": 416, "fenix847mm": 454, "fenix8pro47mm": 454,
    "fenix8solar47mm": 260, "fenix8solar51mm": 280, "fenixe": 416,
    "fr165": 390, "fr165m": 390,
    "fr255": 260, "fr255m": 260, "fr255s": 218, "fr255sm": 218,
    "fr265": 416, "fr265s": 360,
    "fr57042mm": 390, "fr57047mm": 454,
    "fr955": 260, "fr965": 454, "fr970": 454,
    "marq2": 390, "marq2aviator": 390,
    "venu2": 416, "venu2plus": 390, "venu2s": 360,
    "venu3": 454, "venu3s": 390, "venu441mm": 390, "venu445mm": 454,
    "venusq2": 360, "venusq2m": 360, "venux1": 486,
    "vivoactive5": 390, "vivoactive6": 390,
}
# Widest screen per scale, for cropping the landscape.
WIDEST = {2: 240, 3: 280, 4: 416, 5: 454}
# Icons sit next to text, so they use a smaller scale.
ICON_SCALE = {2: 2, 3: 2, 4: 3, 5: 3}


def scale_for(height):
    if height <= 240:
        return 2
    if height <= 280:
        return 3
    if height <= 416:
        return 4
    return 5


def sprites():
    """(resource id, 1x image) for everything; hero frames per outfit."""
    out = []
    for o, outfit in enumerate(OUTFITS):
        pal = recolour(PALETTE, outfit)
        for pose in hero.POSES:
            out.append((f"hero_{o}_{pose}", hero.hero(pose).image(pal)))
    out.append(("land", scene.land().image()))
    out.append(("moon", scene.moon().image()))
    out.append(("cloud_a", scene.drift_cloud(0).image()))
    out.append(("cloud_b", scene.drift_cloud(1).image()))
    out.append(("ride_0", scene.ride_cloud(0).image()))
    out.append(("ride_1", scene.ride_cloud(1).image()))
    out.append(("shadow", scene.shadow().image()))
    out.append(("zzz", scene.zzz().image()))
    out.append(("spark", scene.spark().image()))
    out.append(("twinkle_a", scene.twinkle("Y").image()))
    out.append(("twinkle_b", scene.twinkle("C").image()))
    for i, r in enumerate((3, 5, 7, 9)):
        out.append((f"orb_{i}", scene.orb(r).image()))
    for name in scene.ICONS:
        out.append((f"icon_{name}", scene.icon(name).image()))
    return out


def crop_land(im, p):
    """Keep the rows down to the ground line and just enough width."""
    w = min(im.width, -(-WIDEST[p] // p) + 2)
    x0 = (im.width - w) // 2
    return im.crop((x0, 0, x0 + w, scene.GROUND + 1))


def export_sets(items):
    for p in sorted(set(WIDEST)):
        folder = os.path.join(ROOT, f"resources-art-p{p}")
        shutil.rmtree(folder, ignore_errors=True)
        os.makedirs(folder)
        lines = ["<drawables>"]
        for rid, im in items:
            if rid == "land":
                im = crop_land(im, p)
            k = ICON_SCALE[p] if rid.startswith("icon_") else p
            big = im.resize((im.width * k, im.height * k), Image.NEAREST)
            big.save(os.path.join(folder, rid + ".png"), optimize=True)
            lines.append(f'  <bitmap id="{rid}" filename="{rid}.png" dithering="none" />')
        lines.append("</drawables>")
        with open(os.path.join(folder, "drawables.xml"), "w") as f:
            f.write("\n".join(lines) + "\n")


def write_jungle():
    manifest = open(os.path.join(ROOT, "manifest.xml")).read()
    products = re.findall(r'<iq:product id="([^"]+)"', manifest)
    missing = [d for d in products if d not in SCREEN]
    if missing:
        raise SystemExit(f"unknown screen size for {missing}; add them to SCREEN")
    lines = ["project.manifest = manifest.xml", "", "# Art scale per device, generated by art/export.py."]
    for d in products:
        lines.append(f"{d}.resourcePath = $({d}.resourcePath);resources-art-p{scale_for(SCREEN[d])}")
    with open(os.path.join(ROOT, "monkey.jungle"), "w") as f:
        f.write("\n".join(lines) + "\n")


def write_ids(items):
    poses = list(hero.POSES)
    ids = [rid for rid, _ in items]
    out = [
        "// Generated by art/export.py; do not edit.",
        "import Toybox.Lang;",
        "import Toybox.WatchUi;",
        "",
        "module Art {",
        "  // Art pixels per hero sprite side; screen size = HERO * scale.",
        "  const HERO = 32;",
        f"  const LAND_GROUND = {scene.GROUND};",
    ]
    for i, pose in enumerate(poses):
        out.append(f"  const {pose.upper()} = {i};")
    out.append("")
    out.append("  // Hero frame for outfit 0 (commoner) .. 4 and one of the poses above.")
    out.append("  function hero(outfit as Number, pose as Number) {")
    out.append("    var ids = [")
    rows = []
    for o in range(len(OUTFITS)):
        rows.append("      [" + ", ".join(f"Rez.Drawables.hero_{o}_{p}" for p in poses) + "]")
    out.append(",\n".join(rows))
    out.append("    ];")
    out.append("    return WatchUi.loadResource(ids[outfit][pose]);")
    out.append("  }")
    out.append("}")
    assert all(re.match(r"^[a-z][a-z0-9_]*$", i) for i in ids)
    with open(os.path.join(ROOT, "source", "ArtIds.mc"), "w") as f:
        f.write("\n".join(out) + "\n")


def write_icon():
    """Launcher icon: the flying hero on a cloud under the moon."""
    from pixel import Layer
    L = Layer(40, 40)
    L.disc(20, 20, 19.5, 19.5, "n")
    L.over(scene.moon(), 24, 4)
    L.over(scene.ride_cloud(0), 4, 27)
    L.over(hero.hero("fly0"), 4, 0)
    im = L.image(recolour(PALETTE, "xiaoyao"))
    mask = Layer(40, 40)
    mask.disc(20, 20, 19.5, 19.5, "k")
    alpha = mask.image().getchannel("A")
    im.putalpha(Image.composite(im.getchannel("A"), alpha, alpha))
    im.resize((120, 120), Image.NEAREST).save(os.path.join(ROOT, "resources", "drawables", "launcher_icon.png"))


if __name__ == "__main__":
    items = sprites()
    export_sets(items)
    write_jungle()
    write_ids(items)
    write_icon()
    print(f"exported {len(items)} sprites x {len(WIDEST)} scales")
